---
apiVersion: v2
name: ionoscloud-blockstorage-csi-driver
description: Container Storage Interface (CSI) driver for IONOS Cloud block storage.
type: application
keywords:
  - csi
  - ionos-cloud
version: 0.5.0
appVersion: "v1.9.0-rc.1"
kubeVersion: ">=1.25.0-0"
home: https://github.com/ionos-cloud/ionoscloud-blockstorage-csi-driver
sources:
  - https://github.com/ionos-cloud/ionoscloud-blockstorage-csi-driver
maintainers:
  - name: gfariasalves-ionos
    url: https://github.com/gfariasalves-ionos
  - name: jriedel-ionos
    url: https://github.com/jriedel-ionos
