---
version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "chore:"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "chore:"
