---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driverName }}
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: true
