---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-driver.name" . }}
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "csi-driver.name" . }}
