name: Lint docs

on:
  pull_request:
    paths:
      - '**.md'
      - .github/workflows/lint-docs.yml

jobs:
  markdown-link-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Run link checker
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
