name: Lint docs

on:
  pull_request:

jobs:
  markdown-link-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Run link checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1.0.15
