name: PR check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  validate-title:
    if: github.event.pull_request.draft == false
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
