name: PR check

on:
  pull_request: &filters
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
  pull_request_target: *filters

permissions:
  pull-requests: read

jobs:
  check-pr:
    if: github.event.pull_request.draft == false
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
